
run:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 1

part2: results/output-1.txt results/output-2.txt results/output-3.txt 

part1: results/output-1.txt results/output-2.txt results/output-3.txt results/output-4.txt results/output-5.txt results/output-6.txt results/output-7.txt results/output-8.txt results/output-9.txt results/output-10.txt results/output-11.txt results/output-12.txt results/output-13.txt results/output-14.txt results/output-15.txt results/output-16.txt results/output-17.txt results/output-18.txt results/output-19.txt results/output-20.txt results/output-21.txt results/output-22.txt results/output-23.txt results/output-24.txt results/output-25.txt results/output-26.txt results/output-27.txt results/output-28.txt results/output-29.txt results/output-30.txt 
	bash compute-part-1.sh


results/output-1.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 1

results/output-2.txt:
	time sbcl --dynamic-space-size 8192 --script geodes.cl 2

results/output-3.txt:
	time sbcl --dynamic-space-size 8192 --script geodes.cl 3

results/output-4.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 4

results/output-5.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 5

results/output-6.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 6

results/output-7.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 7

results/output-8.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 8

results/output-9.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 9

results/output-10.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 10

results/output-11.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 11

results/output-12.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 12

results/output-13.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 13

results/output-14.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 14

results/output-15.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 15

results/output-16.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 16

results/output-17.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 17

results/output-18.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 18

results/output-19.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 19

results/output-20.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 20

results/output-21.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 21

results/output-22.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 22

results/output-23.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 23

results/output-24.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 24

results/output-25.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 25

results/output-26.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 26

results/output-27.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 27

results/output-28.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 28

results/output-29.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 29

results/output-30.txt:
	time sbcl --dynamic-space-size 4096 --script geodes.cl 30


clean:
	rm -fv results/*.txt


