

part1: 
	bash ropewalk.sh 2 < input.txt | sort | uniq | wc -l

part2:
	bash ropewalk.sh 10 < input.txt | sort | uniq | wc -l

sample1:
	bash ropewalk.sh 2 < sample-input.txt | sort | uniq | wc -l

sample2:
	bash ropewalk.sh 10 < sample-input.txt | sort | uniq | wc -l
       


clean: 
	rm -fv trail.log
